services:
  web-demo:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "12000"
    volumes:
      - .:/app
      - ./logs:/logs
    env_file:
       - ./.env.production
    user: demotuk
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - demo_network

  db:
    image: postgres:16-alpine
    env_file:
      - ./.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo_network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web-demo 
    networks:
      - demo_network

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  demo_network:
    driver: bridge