services:
  web:
    build:
      context: . # Build context is the current directory (where Dockerfile is)
      dockerfile: Dockerfile # Path to the Dockerfile
    ports:
      - "11000:11000" # Map host port 9000 to container port 9000
    volumes:
      # Mount the current directory into the container's /app directory
      # This allows for live code changes during development (if --reload is used)
      # and ensures the app's files are present.
      - .:/app
      # Mount a volume for TinyDB data persistence
      # This ensures your db.json file persists even if the container is removed.
      # The host path is relative to where docker-compose.yml is located.
      - ./db.json:/app/db.json
      # Mount a volume for logs persistence
      # This allows you to access logs from your host machine in the 'logs' folder.
      - ./logs:/logs
    # Environment variables can be added here if needed, e.g.:
    # environment:
    #   - SOME_VAR=some_value
    # Restart policy to restart the container if it exits
    restart: unless-stopped
